#!/usr/bin/env python3

import iot3.core.mqtt
import iot3.core.otel
import random
import time


def recv(data, topic, payload):
    print(f"{data}: {topic[:16]}: {payload[:16]}")


client_id = random.randbytes(16).hex()
topic = "test/" + random.randbytes(16).hex() + "/iot3"

o = iot3.core.otel.Otel(
    service_name="test-service",
    endpoint="http://localhost:4318",
    batch_period=1,
)
o.start()

c = iot3.core.mqtt.MqttClient(
    client_id=client_id,
    host="test.mosquitto.org",
    port=1883,
    span_ctxmgr_cb=o.span,
    msg_cb=recv,
)
c.start()

c.subscribe(topics=[f"{topic}/+"])

c.publish(topic=f'{topic}/dropped', payload="dropped")
time.sleep(1)

c.publish(topic=f'{topic}/passed', payload="passed")
time.sleep(1)

c.stop()
o.stop()
