#!/usr/bin/env python3

import iot3.core.mqtt
import random
import time


def recv(data, topic, payload):
    print(f"{data}: {topic[:16]}: {payload.decode()[:32]}")


client_id = random.randbytes(16).hex()
topic = "test/" + random.randbytes(16).hex() + "/iot3"

c = iot3.core.mqtt.MqttClient(
    client_id=client_id,
    host="test.mosquitto.org",
    port=1883,
    msg_cb=recv,
    msg_cb_data="clear",
)
c.start()

c.subscribe(topics=[topic])
c.wait_for_ready()
c.publish(topic=topic, payload="clear message")

time.sleep(1)

c.stop()
