#!/usr/bin/env python3

import iot3.core
import time

def recv(data, topic, payload):
    print(f"{topic[:16]}: {payload[:16]}")

iot3.core.start(
    config=iot3.core.sample_config,
    message_callback=recv,
)

iot3.core.wait_for_ready()

iot3.core.subscribe("#")

iot3.core.publish("foo/bar/dropped", "dropped")
time.sleep(1)

iot3.core.publish("foo/bar/passed", "passed")
time.sleep(1)

iot3.core.stop()
