#!/usr/bin/env python3

import math
import sys
import time
from iot3.mobility.gnss import GNSSReport, GNSS

#-----------------------------------------------------------------------------------------
print("Basic, empty GNSS report...")
gnss_report = GNSSReport()

print("GNSSReport with GST fields...")
report = GNSSReport(
    ellipse_semi_major=0.5,
    ellipse_semi_minor=0.3,
    ellipse_orient=90.0,
)
assert report.ellipse_semi_major == 0.5
assert report.ellipse_semi_minor == 0.3
assert report.ellipse_orient == 90.0

print("Disallow explicit timestamp...")
try:
    gnss_report = GNSSReport(
        timestamp=42,
    )
except AttributeError:
    pass
else:
    raise RuntimeError("Timestamp should not be allowed")

print("Validity range...")
try:
    gnss_report = GNSSReport(
        latitude=120,
    )
except AttributeError:
    pass
else:
    raise RuntimeError("Out-of-range latitude should not be allowed")

print("Conflicting attributes...")
try:
    gnss_report = GNSSReport(
        latitude=43.635212,
        latitude_r=1.374562,
    )
except AttributeError:
    pass
else:
    raise RuntimeError("Setting both radians and degrees should not be allowed")

print("Attribute degree -> radian conversion...")
gnss_report = GNSSReport(
    latitude=43.635212,
)
# Can't test floats for equality, so check for a very small delta.
# 10^-9 radians gives ~6mm delta at the surface of Earth at the equator.
if math.fabs(gnss_report.latitude_r - math.radians(43.635212)) >= 10 ** -9:
    raise RuntimeError("Degree -> radian latitude conversion failed")

print("Attribute radian -> degree conversion...")
gnss_report = GNSSReport(
    latitude_r=0.761578119,
)
# Can't test floats for equality, so check for a very small delta.
# 5*10^-8 is about the same as 10^-9 radians, above
if math.fabs(gnss_report.latitude - math.degrees(0.761578119)) >= 5 * 10 ** -8:
    raise RuntimeError("Degree -> radian latitude conversion failed")

print("GNSSReport.Fix unknown...")
fix = GNSSReport.Fix.from_mode_status(mode=None, status=None)
assert fix == GNSSReport.Fix.unknown
assert not fix
assert not fix.is_rtk()

fix = GNSSReport.Fix.from_mode_status(mode=0, status=None)
assert fix == GNSSReport.Fix.unknown
assert not fix
assert not fix.is_rtk()

fix = GNSSReport.Fix.from_mode_status(mode=0, status=2)
assert fix == GNSSReport.Fix.unknown
assert not fix
assert not fix.is_rtk()

print("GNSSReport.Fix no fix...")
fix = GNSSReport.Fix.from_mode_status(mode=1, status=None)
assert fix == GNSSReport.Fix.none
assert not fix
assert not fix.is_rtk()

fix = GNSSReport.Fix.from_mode_status(mode=1, status=2)
assert fix == GNSSReport.Fix.none
assert not fix
assert not fix.is_rtk()

print("GNSSReport.Fix normal fix...")
fix = GNSSReport.Fix.from_mode_status(mode=2, status=None)
assert fix == GNSSReport.Fix.fix_2d
assert fix
assert not fix.is_rtk()

fix = GNSSReport.Fix.from_mode_status(mode=3, status=None)
assert fix == GNSSReport.Fix.fix_3d
assert fix
assert not fix.is_rtk()

print("GNSSReport.Fix enhanced fix...")
fix = GNSSReport.Fix.from_mode_status(mode=2, status=2)
assert fix == GNSSReport.Fix.dgps
assert fix
assert not fix.is_rtk()

fix = GNSSReport.Fix.from_mode_status(mode=2, status=3)
assert fix == GNSSReport.Fix.rtk_fixed
assert fix
assert fix.is_rtk()

fix = GNSSReport.Fix.from_mode_status(mode=2, status=4)
assert fix == GNSSReport.Fix.rtk_float
assert fix
assert fix.is_rtk()

print("GNSSReport.Fix other fix...")
fix = GNSSReport.Fix.from_mode_status(mode=2, status=5)
assert fix == GNSSReport.Fix.other
assert fix
assert not fix.is_rtk()

sys.exit(0)

#-----------------------------------------------------------------------------------------
print("gpsd connection to 127.0.0.1:2948...")
gnss = GNSS(
    host="127.0.0.1",
    port=2948,
)
gnss.start()
for i in range(50):
    time.sleep(0.1)
    if gnss() is not None:
        break
else:
    raise RuntimeError("Can't connect to gpsd on 127.0.0.1:2948, is it running?")
