#
# Software Name : ITSClient
# SPDX-FileCopyrightText: Copyright (c) Orange SA
# SPDX-License-Identifier: MIT
#
# This software is distributed under the MIT license,
# see the "LICENSE.txt" file for more details or https://opensource.org/license/MIT/
#
# Software description: Swift ITS client.
#

strict: true

# ========
# Included
# ========

included:
- ITSClient/Sources
- ITSClient/Tests
- SampleApp/SampleApp

# ==============
# Disabled rules
# ==============

disabled_rules:
- attributes
- conditional_returns_on_newline
- explicit_enum_raw_value
- explicit_type_interface
- extension_access_modifier
- file_name
- file_types_order
- multiline_arguments_brackets
- multiline_parameters_brackets
- opening_brace
- override_in_extension
- strong_iboutlet
- todo
- type_contents_order
- valid_ibinspectable
- vertical_whitespace_between_cases
- vertical_whitespace_opening_braces

# ==============
# Analyzer rules
# ==============

analyzer_rules:
- explicit_self
- unused_import

# =====================================
# Opt-in rules (not enabled by default)
# =====================================

opt_in_rules:
- accessibility_label_for_image
- accessibility_trait_for_button
- array_init
- closure_body_length
- closure_end_indentation
- closure_spacing
- collection_alignment
- contains_over_first_not_nil
- convenience_type
- discouraged_object_literal
- discouraged_optional_boolean
- empty_count
- empty_string
- empty_xctest_method
- explicit_init
- fallthrough
- fatal_error_message
- first_where
- force_unwrapping
- identical_operands
- identifier_name
- implicit_return
- implicitly_unwrapped_optional
- joined_default_parameter
- last_where
- legacy_multiple
- legacy_random
- let_var_whitespace
- literal_expression_end_indentation
- missing_docs
- modifier_order
- multiline_arguments
- multiline_function_chains
- multiline_literal_brackets
- multiline_parameters
- nimble_operator
- no_extension_access_modifier
- nslocalizedstring_key
- nslocalizedstring_require_bundle
- object_literal
- operator_usage_whitespace
- overridden_super_call
- override_in_extension
- prefixed_toplevel_constant
- private_action
- prohibited_super_call
- reduce_into
- redundant_nil_coalescing
- redundant_type_annotation
- redundant_string_enum_value
- required_enum_case
- single_test_class
- sorted_first_last
- sorted_imports
- static_operator
- strict_fileprivate
- strong_iboutlet
- switch_case_alignment
- switch_case_on_newline
- syntactic_sugar
- toggle_bool
- trailing_closure
- trailing_newline
- trailing_whitespace
- type_body_length
- type_name
- unavailable_function
- unneeded_parentheses_in_closure_argument
- unowned_variable_capture
- untyped_error_in_catch
- unused_optional_binding
- vertical_parameter_alignment
- vertical_parameter_alignment_on_call
- vertical_whitespace_closing_braces
- weak_delegate
- yoda_condition

# =============
# Rules details
# =============

closure_body_length:
    warning: 50
    error: 80
    
convenience_type:
    severity: error
    
control_statement:
    severity: error

cyclomatic_complexity:
    warning: 10
    error: 20
    ignores_case_statements: true

file_length:
    warning: 500
    error: 800

force_cast:
    severity: error

function_body_length:
    warning: 50
    error: 80
    
function_parameter_count:
    warning: 8
    error: 10

implicit_getter:
    severity: error

identifier_name:
    max_length:
        warning: 60
        error: 70
    min_length:
        warning: 1
    allowed_symbols:
        - _

large_tuple:
    warning: 3
    error: 4

line_length:
    warning: 120
    error: 200

multiline_arguments:
    severity: error

multiline_function_chains:
    severity: error
    
strict_fileprivate:
    severity: error
    
syntactic_sugar:
    severity: error
    
trailing_comma:
    mandatory_comma: true

trailing_closure:
    only_single_muted_parameter: true

trailing_newline:
    severity: error
    
type_body_length: 250

type_name:
    max_length:
        warning: 50
        error: 60
    min_length:
        warning: 1
    allowed_symbols:
        - _

vertical_parameter_alignment:
    severity: error

vertical_parameter_alignment_on_call:
    severity: error
    
weak_delegate:
    severity: error
