#!/usr/bin/env python3

import glob
import json
import os.path
import sys


def main():
    schemas_dir = os.path.dirname(sys.argv[0])
    schemas = glob.glob(os.path.join(schemas_dir, "*.json"))
    print(json.dumps(sorted(schemas), separators=(",", ":")))


if __name__ == "__main__":
    main()
